ams/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.gateway, name='gateway'),
    path('create_contract/', views.create_contract, name='create_contract'),
    # path('edit_contract/', views.edit_contract, name='edit_contract'),
    # path('user_profile/', views.user_profile, name='user_profile'),
    path('admin_page/', views.admin_page, name='admin_page'),
    path('billing/', views.billing, name='billing'),

    path('monthly_report/', views.monthly_report, name='monthly_report'),
    path('payment_individual/', views.payment_individual, name='payment_individual'),
    path('payment/', views.payment, name='payment'),
    # path('tenant_record/', views.tenant_record, name='tenant_record'),
    path('tenant_comment/', views.tenant_comment, name='tenant_comment'),
    path('report_parameters/', views.report_parameters, name='report_parameters'),
    path('report_type/', views.report_type, name='report_type'),
    path('extra_service/', views.extra_service, name='extra_service'),
    path('elec_cpu_change/', views.elec_cpu_change, name='elec_cpu_change'),
    path('water_cpu_change/', views.water_cpu_change, name='water_cpu_change'),
    path('room_type_rate/', views.room_type_rate, name='room_type_rate'),
    path('current_tenant/', views.current_tenant, name='current_tenant'),
    path('vacant_rooms/', views.vacant_rooms, name='vacant_rooms'),

    path('misc_contents/', views.misc_contents, name='misc_contents'),

    path('send_sms_to_individual_room/', views.send_sms_to_individual_room, name='send_sms_to_individual_room'),
    path('send_general_sms/', views.send_general_sms, name='send_general_sms'),
    path('send_bill_sms_to_all_tenants/', views.send_bill_sms_to_all_tenants, name='send_bill_sms_to_all_tenants'),

    path('tenant_page/', views.tenant_page, name='tenant_page'),

    path('tenant_bill/', views.tenant_bill, name='tenant_bill'),
    path('new_tenant/', views.new_tenant, name='new_tenant'),
    path('pay_rent/str<bref>/', views.pay_rent, name='pay_rent'),

    path('maintenance_charge/', views.maintenance_charge, name='maintenance_charge'),
    path('monthly_report_mini/', views.monthly_report_mini, name='monthly_report_mini'),

    path('confirmation/', views.send_sms_confirmation, name='confirmation'),
    path('send_sms_execution/', views.send_sms_execution, name='send_sms_execution'),

]

ams_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='ams/Chollada_Apartment.html'), name='Chollada_Apartment'),
    path('account/', include('django.contrib.auth.urls')),  # login/logout/password_change/reset
    path('ams/', include('ams.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Chollada Apartment Administration'

ams/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Room_type(models.Model):
    desc = models.CharField(max_length=250)
    rate = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return self.desc


class Room(models.Model):
    room_type = models.ForeignKey(Room_type, on_delete=models.CASCADE)
    room_no = models.CharField(max_length=4)

    def __str__(self):
        return self.room_no


class Extra(models.Model):
    desc = models.CharField(max_length=100)
    cpu = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return self.desc


class Billing(models.Model):
    STATUS_CHOICE = (('open', 'OPEN'), ('close', 'CLOSE'),)

    bill_ref = models.CharField(max_length=6)
    # bill_date = models.DateTimeField(auto_now_add=True)
    bill_date = models.DateField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=5, choices=STATUS_CHOICE, default='open')
    tenant_name = models.CharField(max_length=100)
    room_no = models.CharField(max_length=4)
    room_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    room_acc_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    electricity_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    water_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    common_ser_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    other_ser_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    overdue_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    adjust = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    bill_total = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    payment_date = models.DateField(blank=True, null=True)
    payment_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    cf_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    late_fee = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    maint_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    class Meta:
        ordering = ('-bill_date',)

    def __str__(self):
        return 'Bill for room number: {} Status: {}'.format(self.room_no, self.status)

    def get_absolute_url(self):
        return reverse('pay_rent', args=[str(self.bill_ref)])


# ??? PREPAID ??
class TenantProfile(models.Model):
    tenant = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    pin = models.CharField(max_length=13, unique=True)
    phone = models.CharField(max_length=10)
    room_no = models.OneToOneField(Room, on_delete=models.CASCADE, unique=True)
    term = models.PositiveSmallIntegerField(default=12)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    deposit = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    deduct = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    cum_ovd = models.DecimalField(max_digits=7, decimal_places=2, blank=True, default=0)
    adjust = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    extra = models.ManyToManyField(Extra)
    bill_date = models.DateField(auto_now=True, blank=True)  # ???????????????

    # USE PLACEHOLDER (NO DEFAULT VALUE) INITIAL VALUE TO BE PROVIDED WHEN SAVE TO DB
    elec_unit = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    water_unit = models.DecimalField(max_digits=7, decimal_places=2, null=True)

    late_fee = models.DecimalField(max_digits=7, decimal_places=2, default=0)  # no need to use placeholder
    maint_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return 'Profile for user {}'.format(self.tenant.first_name)

    def get_absolute_url(self):
        return reverse('fill_bill', args=[self.room_no])


class MaintenanceCharge(models.Model):
    STATUS_CHOICE = (('open', 'OPEN'), ('close', 'CLOSE'),)

    room_no = models.ForeignKey(Room, on_delete=models.CASCADE)
    desc = models.CharField(max_length=100)
    # job_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    job_cost = models.DecimalField(max_digits=7, decimal_places=2)  # use placeholder (no default)
    status = models.CharField(max_length=5, choices=STATUS_CHOICE, default='open')
    job_date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-job_date',)

ams/views.py
from .forms import PFormRM101A, PFormRM102A, PFormRM103A, PFormRM104A, PFormRM105A, PFormRM106A
from .forms import PFormRM201A, PFormRM202A, PFormRM203A, PFormRM204A, PFormRM205A, PFormRM206A
from .forms import PFormRM301A, PFormRM302A, PFormRM303A, PFormRM304A, PFormRM305A, PFormRM306A
from .forms import PFormRM201B, PFormRM202B, PFormRM203B, PFormRM204B, PFormRM205B
from .forms import PFormRM301B, PFormRM302B, PFormRM303B, PFormRM304B, PFormRM305B
from .forms import PFormRM401B, PFormRM402B, PFormRM403B, PFormRM404B, PFormRM405B
from .forms import PaymentForm
from .forms import Elec_cpu_change, Water_cpu_change, PhoneNoMessage
from .forms import MaintenanceForm
from .models import Extra, Room, Room_type, MaintenanceCharge, TenantProfile
import datetime
from django.utils.dateparse import parse_datetime, parse_date
from django.utils.timezone import is_aware, is_naive, make_aware, make_naive
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import TenantCreateForm, TenantProfileCreateForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from .forms import RM101A_BillForm, RM102A_BillForm, RM103A_BillForm, RM104A_BillForm, RM105A_BillForm, RM106A_BillForm
from .forms import RM201A_BillForm, RM202A_BillForm, RM203A_BillForm, RM204A_BillForm, RM205A_BillForm, RM206A_BillForm
from .forms import RM301A_BillForm, RM302A_BillForm, RM303A_BillForm, RM304A_BillForm, RM305A_BillForm, RM306A_BillForm
from .forms import RM201B_BillForm, RM202B_BillForm, RM203B_BillForm, RM204B_BillForm, RM205B_BillForm
from .forms import RM301B_BillForm, RM302B_BillForm, RM303B_BillForm, RM304B_BillForm, RM305B_BillForm
from .forms import RM401B_BillForm, RM402B_BillForm, RM403B_BillForm, RM404B_BillForm, RM405B_BillForm
from ams.models import Billing
import random
import calendar

import decimal

import GV

import os
from openpyxl import workbook, load_workbook

# -----SMS FROM LOCALHOST & WEB------------------------------------------
import os
from twilio.rest import Client
from twilio.http.http_client import TwilioHttpClient
# -----------------------------------------------------------------------
import GV


@login_required
def gateway(request):
    if str(request.user) in ['Admin Admin', 'Preecha Bootwicha']:

        return HttpResponseRedirect(reverse_lazy('admin_page'))
    else:
        return HttpResponseRedirect(reverse_lazy('tenant_page'))


@login_required
def create_contract(request):
    if request.method == 'POST':

        tenant_form = TenantCreateForm(data=request.POST)
        # tenant_profile_form = TenantProfileCreateForm(data=request.POST, files=request.FILES)
        tenant_profile_form = TenantProfileCreateForm(data=request.POST, files=request.FILES)

        if tenant_form.is_valid() and tenant_profile_form.is_valid():

            # Create a new tenant object but avoid saving it yet
            new_tenant = tenant_form.save(commit=False)

            # Set the chosen password
            # new_tenant.set_password(tenant_form.cleaned_data['password'])
            new_tenant.set_password(tenant_form.clean_password2())

            # Save the new_tenant object
            new_tenant.save()

            # Create a new tenantprofile object but avoid saving it yet
            tenant_profile = tenant_profile_form.save(commit=False)  # save_m2m() added to tenant_profile_form

            # Set the chosen tenant field
            tenant_profile.tenant = new_tenant

            # ------------------------------------------
            # provide initial value to certain fields before saving to DB
            tenant_profile.elec_unit = 0
            tenant_profile.water_unit = 0
            tenant_profile.misc_cost = 0
            # -----------------------------------------

            # Save the tenantprofile object
            tenant_profile.save()

            # Save the ManyToMany
            tenant_profile_form.save_m2m()

            messages.success(request, 'Profile has been updated successfully')

            return HttpResponseRedirect(reverse_lazy('admin_page'))
        else:
            messages.error(request, 'Error updating your tenant_profile')

    else:
        tenant_form = TenantCreateForm()
        # tenant_profile_form = TenantProfileCreateForm()
        tenant_profile_form = TenantProfileCreateForm()

    return render(request, 'ams/create_contract.html',
                  {'section': 'new_contract', 'tenant_form': tenant_form, 'tenant_profile_form': tenant_profile_form})


# @login_required # ????? #ORIGINAL
def create_bill(room_no):
    pf = get_object_or_404(TenantProfile, room_no__room_no=room_no)
    tname = pf.tenant.first_name + ' ' + pf.tenant.last_name

    rno = pf.room_no.room_no
    adj = pf.adjust

    exd = {}
    exd.setdefault('Electricity CPU', 0)
    exd.setdefault('Water CPU', 0)
    exd.setdefault('Garbage', 0)
    exd.setdefault('Parking', 0)
    exd.setdefault('Wifi', 0)
    exd.setdefault('Cable TV', 0)
    exd.setdefault('Bed', 0)
    exd.setdefault('Bed accessories', 0)
    exd.setdefault('Dressing Table', 0)
    exd.setdefault('Clothing Cupboard', 0)
    exd.setdefault('TV Table', 0)
    exd.setdefault('Fridge', 0)
    exd.setdefault('Air-Conditioner', 0)

    for e in pf.extra.all():
        exd.update({e.desc: e.cpu})

    room_cost = pf.room_no.room_type.rate
    room_acc_cost = exd['Bed'] + exd['Bed accessories'] + exd['Dressing Table'] \
                    + exd['Clothing Cupboard'] + exd['TV Table'] + exd['Fridge'] \
                    + exd['Air-Conditioner']

    elec_cost = exd['Electricity CPU'] * pf.elec_unit
    water_cost = exd['Water CPU'] * pf.water_unit

    com_ser_cost = pf.elec_unit * GV.COMMOM_SERVICE_CPU

    oth_ser_cost = exd['Garbage'] + exd['Parking'] + exd['Wifi'] + exd['Cable TV']
    ovd_amt = pf.cum_ovd

    # -----------------------
    late_f = pf.late_fee
    maint_c = pf.maint_cost

    # RESET pf.late_fee & pf.maint_cost TO O TO BE READY FOR NEXT CYCLE
    pf.late_fee = 0
    pf.maint_cost = 0
    # -----------------------

    total = room_cost + room_acc_cost + elec_cost + water_cost + com_ser_cost + oth_ser_cost + ovd_amt + adj + late_f + maint_c

    # CREATE PRELIMINARY BILL OBJECT **************
    new_bill = Billing(bill_ref=get_ref_string(),
                       bill_date=datetime.datetime.now().date(),  # SUPPLY BILL DATE
                       tenant_name=tname,
                       room_no=rno,
                       room_cost=room_cost,
                       room_acc_cost=room_acc_cost,
                       electricity_cost=elec_cost,
                       water_cost=water_cost,
                       common_ser_cost=com_ser_cost,
                       other_ser_cost=oth_ser_cost,
                       overdue_amount=ovd_amt,

                       # -----------------------
                       late_fee=late_f,
                       maint_cost=maint_c,
                       # -----------------------

                       adjust=adj,
                       bill_total=total,

                       )

    # SAVE TENANTPROFILE OBJECT TO DB
    pf.save()

    # ADJUST PRELIMINARY BILL OBJECT
    adjust_bill(pf, new_bill)


def adjust_bill(pf, new_bill):
    tn_bill = new_bill

    bref = tn_bill.bill_ref
    bdate = tn_bill.bill_date
    # bupd # TO BE FILLED WHEN SAVED
    # bstat # TO BE FILLED WHEN SAVED
    tname = tn_bill.tenant_name
    rno = tn_bill.room_no
    room_cost = tn_bill.room_cost
    room_acc_cost = tn_bill.room_acc_cost
    elec_cost = tn_bill.electricity_cost
    water_cost = tn_bill.water_cost
    com_ser_cost = tn_bill.common_ser_cost
    oth_ser_cost = tn_bill.other_ser_cost
    ovd_amt = tn_bill.overdue_amount
    adj = tn_bill.adjust
    # total = tn_bill.bill_total # TO BE ADJUSTED IF REQUIRED

    # pay_date # TO BE FILLED AT PAYMENT
    # pay_amt #TO BE FILL AT PAYMENT
    # bf #TO BE FILLED AT PAYMENT

    late_f = tn_bill.late_fee
    maint_c = tn_bill.maint_cost

    sdate = pf.start_date  # FROM pf

    start_day = sdate.day
    bill_day = bdate.day

    start_m = sdate.month
    bill_m = bdate.month

    number_of_day_in_start_month = calendar.monthrange(sdate.year, sdate.month)[1]
    nodsm = number_of_day_in_start_month
    number_of_day_in_bill_month = calendar.monthrange(bdate.year, bdate.month)[1]
    nodbm = number_of_day_in_bill_month

    if abs(start_m - bill_m) == 0:
        tbd = number_of_day_in_bill_month - start_day + 1  # SPECIAL CASE 1
    elif abs(start_m - bill_m) == 1 and start_day >= bill_day:
        tbd = number_of_day_in_bill_month + (number_of_day_in_start_month - start_day + 1)  # SPECIAL CASE 2
    else:
        tbd = number_of_day_in_bill_month  # ONGOING CASE

    # ADJUST CERTAIN VALUES IN PRELIM. BILL OBJECT
    const = decimal.Decimal((tbd / nodbm))

    room_cost = room_cost * const
    room_acc_cost = room_acc_cost * const
    com_ser_cost = com_ser_cost * const
    oth_ser_cost = oth_ser_cost * const
    adj = adj * const

    total = (room_cost + room_acc_cost + adj) + elec_cost + water_cost + (
            com_ser_cost + oth_ser_cost) + ovd_amt + late_f + maint_c

    # CREATE FINAL BILL OBJECT *******************
    new_bill = Billing(bill_ref=bref,
                       tenant_name=tname,
                       room_no=rno,
                       room_cost=room_cost,
                       room_acc_cost=room_acc_cost,
                       electricity_cost=elec_cost,
                       water_cost=water_cost,
                       common_ser_cost=com_ser_cost,
                       other_ser_cost=oth_ser_cost,
                       overdue_amount=ovd_amt,

                       # -----------------------
                       late_fee=late_f,
                       maint_cost=maint_c,
                       # -----------------------

templates/ams/Chollada_Apartment.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Chollada Apartment{% endblock %}</title>

    <link href="{% static "css/header.css" %}" rel="stylesheet">

    {% block script %}
    {% endblock %}

    <style>
        #content {
            height: 1080px;
            background-image: url("/static/pics/hp4.jpg");
            background-size: contain;
            background-repeat: no-repeat;
        }
    </style>

    {% block style %}
    {% endblock %}


</head>
<body>
<div id="header">

    <span class="logo">Chollada Apartment Homepage</span>


    <span class="user">
          {% if request.user.is_authenticated %}
              Hello {{ request.user.first_name }},
              <a href="{% url "logout" %}">Logout</a>
          {% else %}
              <a href="{% url "login" %}">Log-in</a>
          {% endif %}
        </span>
</div>

<div id="content">
    {% block content %}
    {% endblock %}


</div>
</body>

</html>

templates/ams/confirmation.html
{% extends "ams_admin_base_html.html" %}
{% load static %}
{% load humanize %}

{% block title %}Electricity CPU{% endblock %}

{% block script %}
    <link href="{% static "css/ams_body.css" %}" rel="stylesheet">
{% endblock %}

{% block style %}

    <style>
        div.submit button {
            width: 6em;
            font-size: large;
            background-color: red;
            color: white;
            margin-top: .5em;
            padding: .3em;
        }
    </style>

{% endblock %}


{% block content %}

    <form name="radio_bt" action="{% url "send_sms_execution" %}" method="post">
        {% csrf_token %}

        <strong>Are you sure you want to send SMS to {{ total_opb }} of {{ total_tenant }} rooms ?</strong><br><br>

        <input type="radio" id="yes" name="radbt" value="go">
        <label for="yes">YES</label><br><br>

        <input type="radio" id="no" name="radbt" value="ng" checked>
        <label for="no">NO</label><br><br>


        <div class="submit">
            <button type="submit">Confirm</button>
        </div>

    </form>

{% endblock %}

templates/ams/current_tenant.html
{% extends "ams_admin_base_html.html" %}

{% load account_tags %}
{% load ams_tags %}

{% load static %}
{% load humanize %}

{% block title %}Current tenants{% endblock %}

{% block script %}
    <link href="{% static "css/ams_body.css" %}" rel="stylesheet">
{% endblock %}

{% block style %}

    <style>


        div #hx {
            float: left;
        }

        div #da {
            clear: both;
        }

        #hrn {

            display: block;
            width: 3em;
            color: white;
            background-color: blue;
            float: left;
            text-align: left;
            font-size: medium;
        }

        #hname {

            display: block;
            width: 12em;
            color: white;
            background-color: blue;
            float: left;
            text-align: left;
            font-size: medium;
        }

        #hhp {

            display: block;
            width: 7em;
            color: white;
            background-color: blue;
            float: left;
            text-align: center;
            font-size: medium;
        }

        #hpin {

            display: block;
            width: 8em;
            color: white;
            background-color: blue;
            float: left;
            text-align: center;
            font-size: medium;
        }

        #hsd {

            display: block;
            width: 8em;
            color: white;
            background-color: blue;
            float: left;
            text-align: right;
            font-size: medium;
        }

        #hrmc, #hadj, #hovd,
        #hrmacc, #hrmoc, #hdepo {

            display: block;
            width: 4em;
            color: white;
            background-color: blue;
            float: left;
            text-align: right;
            font-size: medium;
        }

        .rn {

            display: block;
            width: 3em;
            color: red;
            float: left;
            text-align: left;
            font-size: medium;
        }

        .name {

            display: block;
            width: 12em;
            float: left;
            text-align: left;
            font-size: medium;
        }

        .hp {

            display: block;
            width: 7em;
            float: left;
            text-align: center;
            font-size: medium;
        }

        .pin {

            display: block;
            width: 8em;
            float: left;
            text-align: center;
            font-size: medium;
        }

        .sd {

            display: block;
            width: 8em;
            float: left;
            text-align: right;
            font-size: medium;
        }

        .rmc, .adj, .ovd,
        .rmacc, .rmoc, .depo {

            display: block;
            width: 4em;
            float: left;
            text-align: right;
            font-size: medium;
        }

    </style>

{% endblock %}


{% block content %}
    <h2>Current Tenants as of {{ current_dt }} : [{{ total_tn }}]</h2>

    <div id="hx">
        <label id="hrn">RNO</label>
        <label id="hname">NAME</label>
        <label id="hhp">HP</label>
        <label id="hrmc">RMC</label>
        <label id="hrmacc">RAC</label>
        <label id="hrmoc">OSC</label>
        <label id="hdepo">DEPO</label>
        <label id="hadj">ADJ</label>
        <label id="hovd">OVD</label>
        <label id="hsd">S-DATE</label>
        <br>
    </div>

    <div id="da">

        {% for tn in cur_tenant %}
            <span class="rn">{{ tn.room_no }}</span>
            <span class="name">{{ tn.tenant }}</span>
            <span class="hp">{{ tn.phone }}</span>
            <span class="rmc">{{ tn.room_no.room_type.rate|floatformat:0|intcomma }}</span>
            <span class="rmacc">{% room_acc_cost tn.room_no.room_no %}  </span>
            <span class="rmoc">{% room_other_cost tn.room_no.room_no %} </span>
            <span class="depo">{{ tn.deposit|floatformat:0|intcomma }}</span>
            <span class="adj">{{ tn.adjust|floatformat:0|intcomma }}</span>
            <span class="ovd">{{ tn.cum_ovd|floatformat:0|intcomma }}</span>
            <span class="sd">{{ tn.start_date }}</span><br>
        {% endfor %}

    </div>

{% endblock %}

templates/ams/display_tenant_data.html
<span class="name">{{ tenant_data.tenant.first_name }} {{ tenant_data.tenant.last_name }}</span>
<span class="phone">{{ tenant_data.phone }}</span>
<span class="room">{{ tenant_data.room_no }}</span>

templates/ams/extra_service.html
{% extends "ams_admin_base_html.html" %}
{% load static %}
{% load humanize %}

{% block title %}Extra Service Report{% endblock %}

{% block script %}
    <link href="{% static "css/ams_body.css" %}" rel="stylesheet">
{% endblock %}

{% block style %}

    <style>

        div #hx {
            float: left;
        }

        div #hx #hdesc {

            display: block;
            width: 12em;
            color: white;
            background-color: blue;
            float: left;
            text-align: left;
            font-size: medium;
        }

        div #hx #hcpu {

            display: block;
            width: 7em;
            color: white;
            background-color: blue;
            float: left;
            text-align: right;
            font-size: medium;
        }

        div #da {
            clear: both;
        }

        div #da .desc {
            display: block;
            width: 12em;
            text-align: left;
            float: left;
            font-size: medium;
        }

        div #da .cpu {
            display: block;
            width: 7em;
            text-align: right;
            float: left;
            font-size: medium;
        }

        a:hover {
            color: red;
            font-weight: bold;
        }


    </style>

{% endblock %}


{% block content %}
    <h2>Extra-Service Rates( {{ current_dt }} )</h2>

    <div id="hx">
        <label id="hdesc">Description</label>
        <label id="hcpu">Rate</label>
        <br>
    </div>
    <div id="da">
        {% for e in extra %}
            <span class="desc">{{ e.desc }}</span>
            {% if e.desc == 'Electricity CPU' %}
                <a class="cpu" href="{% url 'elec_cpu_change' %}"> {{ e.cpu|floatformat:2|intcomma }}</a><br>
            {% else %}
                {% if e.desc == 'Water CPU' %}
                    <a class="cpu" href="{% url 'water_cpu_change' %}"> {{ e.cpu|floatformat:2|intcomma }}</a><br>
                {% else %}
                    <span class="cpu">{{ e.cpu|floatformat:0|intcomma }}</span><br>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

templates/ams/maintenanace_charge.html
{% extends "ams_admin_base_html.html" %}

{% load staticfiles %}
{#{% load widget_tweaks %}#}

{% block title %}New maintenance charge{% endblock %}

{% block script %}

    <link href="{% static "css/ams_body.css" %}" rel="stylesheet">

{% endblock %}


{% block style %}
    <style>

        #content {
            font: 90% Arial, Helvetica, sans-serif;
            width: 95%;
            padding: 2em;
            margin: 2px;
        }

        #lb1, #lb2 {
            display: block;
            color: black;
            width: 6em;

            line-height: 1.5em;

            font-weight: normal;
            text-align: right;
            margin-right: .25em;
            background-color: #aaaaaa;
            float: left;

        }

        div .ma_cost #id_room_no,
        div .ma_cost #id_job_cost {
            width: 6em;

            font-size: 100%;

            text-align: center;

            background-color: lightskyblue;
            margin-top: 0;

            float: left;
        }

        div .ma_cost fieldset {
            width: 18em;
            height: 8em;
        }

        div .ma_cost legend {
            color: blue;
            font-weight: bold;
            font-size: 125%;
            margin-bottom: .5em;
        }

        div .submit button {
            width: 6em;
            font-size: large;
            background-color: red;
            color: white;
            margin-top: .5em;
            padding: .3em;
            clear: both;
        }
    </style>

{% endblock %}


{% block content %}
    <form action="." method="post">

        {% csrf_token %}
        <div class="ma_cost">
            <fieldset>
                <legend align="top">MAINTENANCE CHARGE</legend>
                <label for="id_room_no" id="lb1">ROOM NO:</label>{{ maintenance_form.room_no }} <br><br>
                <label for="id_job_cost" id="lb2">COST:</label>{{ maintenance_form.job_cost }}
            </fieldset>
        </div>

        <div class="submit">
            <button type="submit">Submit</button>
        </div>


    </form>



{% endblock %}